name: Keep Server Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to keep backend active
        run: curl -X GET https://pern-chat-app-4dzt.onrender.com/
